# Generated by Django 5.0.6 on 2024-06-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('Description', models.TextField()),
                ('ing', models.ImageField(upload_to='static/lots_img/')),
                ('end', models.BooleanField(default=False)),
                ('end_time', models.CharField(max_length=10)),
                ('recipient', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Lots_are_over',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('Description', models.TextField()),
                ('ing', models.ImageField(upload_to='static/lots_img/')),
                ('sent', models.BooleanField(default=False)),
                ('recipient', models.EmailField(blank=True, default='', max_length=254, verbose_name='email address')),
            ],
        ),
    ]
