# Generated by Django 5.0.6 on 2024-06-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
    ]
