# Generated by Django 5.0.6 on 2024-06-14 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_app', '0002_alter_lots_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lots',
            name='auction_step',
            field=models.IntegerField(default=30),
        ),
    ]
