# Generated by Django 5.0.6 on 2024-06-14 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controll_app', '0003_lots_auction_step'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lots',
            name='auction_step',
            field=models.IntegerField(),
        ),
    ]
